### PR TITLE
Added support for Redox OS.

### PR DESCRIPTION
**Pull request by goyox86**
Hello there!

I was porting [Exa](https://github.com/ogham/exa) to (Redox OS)[https://redox-os.org/] and I realized that depended on this library and I added support to Redox in a branch.

I've tested it in Redox and works like a charm.

Let me know if you need anything.

Nice library anyway, very easy to port!

### CODE REVIEW

**Comment by ogham** [comment]
Hi! Thanks for the PR. However I'm a little confused at what this commit actually does! I've heard of Redox as an OS written in Rust but I'm not familiar with its internals.

It looks like you've ported the function so that instead of using `libc` it uses `redox_syscall`. Then, when someone compiles exa under Redox, it gets that crate as an interface to the OS operations, like the `libc` crate does now, and uses it to make the system call. Is that right? Currently getting the current date is one of the few unsafe parts of the library so it would be nice to use a safe wrapper if possible.

Also, what happens when you try to use `libc` under Redox -- does anything work?

**Comment by goyox86** [comment]
H @ogham!

Yeah when somebody compiles the crate targeting Redox the crate will be pulled and used to interface with Redox OS. I'm sorry if I did not explained myself well. Basically Redox is completely built in Rust and as such, it has Rust support even at system call level AKA no need for `libc` crate. 

Also thanks for pointing out that that function I just defined was `unsafe` It did not needed to! (That's the whole point of the `redox_syscall` crate) . It is safe now, as a result I had to conditionally suppress some warnings related to a unused unsafe in Redox.

While I was compiling under Linux I saw a few warnings (about unneeded casts to `i64`) and I fixed them too (I can put that code back if you request it)

Let me know if you have any other questions!

**Comment by goyox86** [comment]
🏓

**Comment by ogham** [comment]
Sorry, I dropped the ball on this. Thanks again for the PR and the helpful 🏓.

**Comment by ogham** [comment]
I need to fix https://github.com/ogham/exa/issues/189 in exa so this (and the other datetime crates) will be released to Crates when I next get a chance.

**Pull request merged**
